// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://intboloma5b7bcnn5h3o4b6ylu.appsync-api.ap-northeast-2.amazonaws.com/graphql',
          region: 'ap-northeast-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-qdvcqh2x7bd55pzhwwaqe6k5yi'
        }
    }
};

export default config;