name: Deploy Admin to GitHub Pages

# Deploy admin page to /admin subdirectory

on:
  push:
    branches: [ development, main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: |
        flutter --version
        flutter pub get
    
    - name: Create empty .env file
      run: |
        echo "# Environment variables" > .env
        echo "Created .env file"
      
    - name: Build for web (Admin)
      run: |
        flutter build web \
          --target lib/admin_main.dart \
          --base-href "/dating_meet_app/admin/" \
          --release
      
    - name: List build output
      run: |
        echo "Build directory contents:"
        ls -la build/web/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        destination_dir: admin
        keep_files: true